- name: Run extractor for public channels (with debug)
        shell: bash
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          echo "=== Listing .github/scripts ==="
          ls -la .github || true
          ls -la .github/scripts || true
          echo "=== channel_map.txt contents ==="
          if [ -f channel_map.txt ]; then
            sed -n '1,200p' channel_map.txt
          else
            echo "channel_map.txt not found"
            exit 0
          fi
          echo "=== Running extractors ==="
          mapfile -t lines < channel_map.txt
          for l in "${lines[@]}"; do
            [[ -z "$l" || "$l" =~ ^# ]] && continue
            key=$(printf '%s' "$l" | cut -d'|' -f1)
            page=$(printf '%s' "$l" | cut -d'|' -f2)
            type=$(printf '%s' "$l" | cut -d'|' -f3)
            echo "Processing entry: key=$key type=$type page=$page"
            if [ "$type" = "public" ]; then
              if [ -f ".github/scripts/extract_and_update.sh" ]; then
                echo "Calling extractor for $key"
                bash ./.github/scripts/extract_and_update.sh "$key" "$page" || echo "extract failed for $key"
              else
                echo "ERROR: extractor script not found at .github/scripts/extract_and_update.sh"
              fi
            else
              echo "Skipping $key (type=$type); manual/interactive flow required."
            fi
          done
