name: Refresh IPTV playlist (public channels)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes; change if you like

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with write)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python (for yt-dlp)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp || true
          sudo apt-get update -y
          sudo apt-get install -y curl jq || true
          mkdir -p .tmp_data

      - name: Run extractor for public channels
        shell: bash
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          if [ ! -f channel_map.txt ]; then
            echo "channel_map.txt not found, exiting."
            exit 0
          fi
          mapfile -t lines < channel_map.txt
          for l in "${lines[@]}"; do
            [[ -z "$l" || "$l" =~ ^# ]] && continue
            key=$(printf '%s' "$l" | cut -d'|' -f1)
            page=$(printf '%s' "$l" | cut -d'|' -f2)
            type=$(printf '%s' "$l" | cut -d'|' -f3)
            if [ "$type" = "public" ]; then
              echo "Running extractor for $key -> $page"
              ./.github/scripts/extract_and_update.sh "$key" "$page" || echo "extract failed for $key"
            else
              echo "Skipping $key (type=$type); manual/interactive flow required."
            fi
          done

      - name: Show diff
        run: git --no-pager diff --staged || git --no-pager diff || true

      - name: Commit & push updates (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add in_custom.m3u || true
          if ! git diff --staged --quiet; then
            git commit -m "Auto-refresh playlist: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
