name: Auto Update Shemaroo

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:        # lets you run manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get fresh Shemaroo link
        run: |
          LINK=$(curl -s "https://www.shemaroome.com/all-channels/shemaroo-marathibana" \
          | grep -oP 'https.*?playlist.m3u8[^"]*' | head -n 1)
          echo "Fresh link: $LINK"

          # Replace expired Shemaroo link in in.m3u
          sed -i "s|https://cdn.live.shemaroome.com.*|$LINK|" in.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add in.m3u
          git commit -m "Auto update Shemaroo link"
          git push
