name: Auto Update Shemaroo

on:
  workflow_dispatch:        # allows manual trigger from GitHub UI
  schedule:
    - cron: "0 */3 * * *"   # run automatically every 3 hours

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug - list repo files
        run: |
          echo "Repo files:"
          ls -la

      - name: Get fresh Shemaroo link
        id: getlink
        run: |
          LINK=$(curl -s "https://www.shemaroome.com/all-channels/shemaroo-marathibana" \
          | grep -oP 'https.*?playlist\.m3u8[^"]*' | head -n 1)

          echo "Fresh link: $LINK"

          if [ -z "$LINK" ]; then
            echo "ERROR: Could not fetch Shemaroo link"
            exit 1
          fi

          echo "::set-output name=link::$LINK"

      - name: Replace Shemaroo link in playlist
        run: |
          PLAYLIST_FILE="in_custom.m3u"   # <-- change if your file has a different name
          NEWLINK="${{ steps.getlink.outputs.link }}"

          if [ ! -f "$PLAYLIST_FILE" ]; then
            echo "Playlist file not found: $PLAYLIST_FILE"
            exit 1
          fi

          sed -i "s|https://cdn.live.shemaroome.com.*|$NEWLINK|" "$PLAYLIST_FILE"

          echo "Updated Shemaroo link in $PLAYLIST_FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto update Shemaroo link" || echo "No changes to commit"
          git push
